release:
  # Repo in which the release will be created.
  github:
    owner: taubyte
    name: dreamland

  # Control the draft and prerelease settings
  draft: false
  replace_existing_draft: false
  prerelease: auto

  # Release naming and SCM interaction
  name_template: ""
  disable: false
  skip_upload: false
  
builds:
  - id: "linux"
    main: "main.go"
    binary: "dreamland"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOAMD64=v2


changelog:
  skip: true

checksum:
  disable: true

archives:
  - files:
    - none*
